(specifications->manifest
  (list "jupyter"
        "emacs-jupyter"
        "guix-jupyter"
        "python"
        "python-ipython"
        "python-ipykernel"
        "python-pytest"
        "python-beautifulsoup4"
        "python-pandas"
        "python-seaborn"
        "python-sqlalchemy"
        "python-osmnx"
        "bash"
        "font-google-noto"
        "sqlite"))
